# mysql-notification-statefulset.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-notification-headless
  labels:
    app: mysql-notification
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: mysql-notification
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-notification
  labels:
    app: mysql-notification
spec:
  serviceName: mysql-notification-headless
  replicas: 1
  selector:
    matchLabels:
      app: mysql-notification
  template:
    metadata:
      labels:
        app: mysql-notification
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notification-db-secret
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: notification-db-secret
              key: database
        # 优化 MySQL 启动速度和内存使用
        - name: MYSQL_INIT_CONNECT
          value: "SET autocommit=1"
        - name: MYSQL_SKIP_NAME_RESOLVE
          value: "1"
        # 添加 MySQL 性能优化配置
        - name: MYSQL_INNODB_BUFFER_POOL_SIZE
          value: "256M"
        - name: MYSQL_INNODB_LOG_FILE_SIZE
          value: "32M"
        - name: MYSQL_INNODB_FLUSH_METHOD
          value: "O_DIRECT"
        - name: MYSQL_MAX_CONNECTIONS
          value: "50"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "512Mi"  # 增加内存请求以支持 MySQL 8.0
            cpu: "100m"      # 减少 CPU 请求
          limits:
            memory: "1Gi"    # 增加内存限制以支持 MySQL 8.0
            cpu: "500m"      # 保持 CPU 限制
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
# 修改Service名称与Secret中的host保持一致
apiVersion: v1
kind: Service
metadata:
  name: mysql-notification-service  # 修改为与Secret中host相同的名称
spec:
  selector:
    app: mysql-notification
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP